# Generated by Django 4.2 on 2025-04-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format',
        ),
    ]
